apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: isitfriday
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: isitifriday
    app.kubernetes.io/name: flask
    app.kubernetes.io/instance: isitfriday-frontend
    app.kubernetes.io/managed-by: tekton
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.6
  name: isitfriday
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: isitfriday
    weight: 100
  wildcardPolicy: None
